// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgsbfqspfczmtbrimlzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnc2JmcXNwZmN6bXRicmltbHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzYyMDEsImV4cCI6MjA2NDcxMjIwMX0.a0yi54SJK9X2HD5I7_FqG2nuOmkqC2gg4ZOZ8Hxzwxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);